<?php

namespace Database\Seeders;

use App\Models\Child;
use Illuminate\Database\Seeder;

class ChildSeeder extends Seeder
{
    public function run(): void
    {
        $children = [
            [
                'nom' => 'MWANZA',
                'post_nom' => 'KILOLO',
                'prenom' => 'Emmanuel',
                'date_naissance' => '2015-03-10',
                'genre' => 'Masculin',
                'etat_civil' => 'Célibataire',
                'email' => 'emmanuel.mwanza@parent.cd',
                'telephone' => '+243900001001',
                'adresse' => 'Lubumbashi, RDC',
                'nom_pere' => 'MWANZA Jean',
                'nom_mere' => 'KILOLO Marie',
                'telephone_parent1' => '+243900001000',
                'telephone_parent2' => '+243900001002',
                'email_parents' => 'parents.mwanza@email.cd',
                'contact_urgence' => '+243900001003',
                'lien_contact_urgence' => 'Oncle',
                'date_conversion' => '2023-06-15',
                'date_bapteme' => null,
                'baptise_saint_esprit' => 'Non',
                'vie_donnee_a_jesus' => 'Oui',
                'est_ouvrier' => false,
                'date_adhesion' => '2020-01-15',
                'allergies_connues' => false,
                'maladies' => null,
                'autorisation_soins' => true,
            ],
            [
                'nom' => 'LUBOYA',
                'post_nom' => 'MONGA',
                'prenom' => 'Sarah',
                'date_naissance' => '2014-07-22',
                'genre' => 'Féminin',
                'etat_civil' => 'Célibataire',
                'email' => 'sarah.luboya@parent.cd',
                'telephone' => '+243900002001',
                'adresse' => 'Kinshasa, RDC',
                'nom_pere' => 'LUBOYA Paul',
                'nom_mere' => 'MONGA Grace',
                'telephone_parent1' => '+243900002000',
                'telephone_parent2' => '+243900002002',
                'email_parents' => 'parents.luboya@email.cd',
                'contact_urgence' => '+243900002003',
                'lien_contact_urgence' => 'Tante',
                'date_conversion' => '2022-12-25',
                'date_bapteme' => '2024-01-07',
                'baptise_saint_esprit' => 'Oui',
                'vie_donnee_a_jesus' => 'Oui',
                'est_ouvrier' => true,
                'commission_actuelle' => 'Louange',
                'date_adhesion' => '2019-09-10',
                'allergies_connues' => true,
                'allergies_details' => 'Allergie aux arachides',
                'maladies' => 'Asthme léger',
                'traitement' => 'Inhalateur en cas de crise',
                'autorisation_soins' => true,
            ],
            [
                'nom' => 'NKULU',
                'post_nom' => 'TSHIBANGU',
                'prenom' => 'Daniel',
                'date_naissance' => '2016-11-05',
                'genre' => 'Masculin',
                'etat_civil' => 'Célibataire',
                'email' => 'daniel.nkulu@parent.cd',
                'telephone' => '+243900003001',
                'adresse' => 'Kolwezi, RDC',
                'nom_pere' => 'NKULU David',
                'nom_mere' => 'TSHIBANGU Rachel',
                'telephone_parent1' => '+243900003000',
                'telephone_parent2' => '+243900003002',
                'email_parents' => 'parents.nkulu@email.cd',
                'contact_urgence' => '+243900003000',
                'lien_contact_urgence' => 'Père',
                'date_conversion' => null,
                'date_bapteme' => null,
                'baptise_saint_esprit' => 'Non',
                'vie_donnee_a_jesus' => 'Non',
                'est_ouvrier' => false,
                'date_adhesion' => '2021-05-20',
                'allergies_connues' => false,
                'autorisation_soins' => true,
            ],
            [
                'nom' => 'KALALA',
                'post_nom' => 'ILUNGA',
                'prenom' => 'Ruth',
                'date_naissance' => '2013-02-14',
                'genre' => 'Féminin',
                'etat_civil' => 'Célibataire',
                'email' => 'ruth.kalala@parent.cd',
                'telephone' => '+243900004001',
                'adresse' => 'Likasi, RDC',
                'nom_pere' => 'KALALA Joseph',
                'nom_mere' => 'ILUNGA Esther',
                'telephone_parent1' => '+243900004000',
                'telephone_parent2' => '+243900004002',
                'email_parents' => 'parents.kalala@email.cd',
                'contact_urgence' => '+243900004003',
                'lien_contact_urgence' => 'Grand-mère',
                'date_conversion' => '2021-08-15',
                'date_bapteme' => '2023-04-09',
                'baptise_saint_esprit' => 'Non',
                'vie_donnee_a_jesus' => 'Oui',
                'est_ouvrier' => true,
                'commission_actuelle' => 'Intercession',
                'commission_souhaitee' => 'Évangélisation',
                'date_adhesion' => '2018-03-12',
                'allergies_connues' => false,
                'autorisation_soins' => true,
            ],
            [
                'nom' => 'MUJINGA',
                'post_nom' => 'KABWE',
                'prenom' => 'Samuel',
                'date_naissance' => '2017-09-28',
                'genre' => 'Masculin',
                'etat_civil' => 'Célibataire',
                'email' => 'samuel.mujinga@parent.cd',
                'telephone' => '+243900005001',
                'adresse' => 'Lubumbashi, RDC',
                'nom_pere' => 'MUJINGA Samuel Sr',
                'nom_mere' => 'KABWE Deborah',
                'telephone_parent1' => '+243900005000',
                'telephone_parent2' => '+243900005002',
                'email_parents' => 'parents.mujinga@email.cd',
                'contact_urgence' => '+243900005000',
                'lien_contact_urgence' => 'Père',
                'date_conversion' => '2024-03-31',
                'date_bapteme' => null,
                'baptise_saint_esprit' => 'Non',
                'vie_donnee_a_jesus' => 'Oui',
                'est_ouvrier' => false,
                'date_adhesion' => '2022-01-08',
                'allergies_connues' => false,
                'autorisation_soins' => true,
            ],
        ];

        foreach ($children as $child) {
            Child::create($child);
        }
    }
}
